### PR TITLE
kubeadm: remove the unit test TestRunListTokens

### PR DESCRIPTION
**Pull request by rdodev**
Remove the test based on these points:

- it's apparently flaky by more than one reports and it's hard to debug.
- it's not a CLI unit test.
- it's testing API objects using a fake API server which is a bad hack...
- existing e2e tests already provide coverage for all
the `expectedError: false` cases.

(cherry picked from commit f337f0e580ea05860eb0411b0fe938f22bc496b1)

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by rdodev** [comment]
I've honestly no idea what 'pull bazel diff' in this context means.

**Comment by ncdc** [comment]
https://github.com/heptio/kubernetes/commit/f337f0e580ea05860eb0411b0fe938f22bc496b1#diff-91317c8a3ae3c5b4b1ad8611265565c8

**Comment by rdodev** [comment]
Oh weird why it didn't come through with the cherry-pick

`hub cherry-pick -x f337f0e580ea05860eb0411b0fe938f22bc496b1`

**Comment by rdodev** [comment]
bazel diff pulled

**Comment by ncdc** [comment]
Actually, doesn't need a squash. Just fix commit 2 (comment, email)

**Comment by ncdc** [comment]
LGTM

**Pull request merged**
